# 1. Choose OS (Ubuntu 14.04.3 LTS Server Edition 64bit, ~2 CORE, 7.5GB RAM)
sudo: required
dist: trusty

# 2. Choose language and target JDKs for parallel builds.
language: java
jdk:
  - oraclejdk8

# 3. Setup cache directory for SBT and Maven.
cache:
  directories:
  - $HOME/.m2

# 4. Run maven install before running lint-java.
install:
  - export MAVEN_SKIP_RC=1
  - mvn -T 4 -q -DskipTests clean install 
